### ISSUE TITLE
how to extend the user model?

### ISSUE THREAD

**Issue by toddgeist** [tjwebb/sails-auth#110]
Is there a way to extend the User model with additional Attributes?

**Comment by toddgeist** [comment]
answering my own question...


in `api/models/User.js`
just add the additional attributes you want.  Like this
```
module.exports = {
  attributes: {

    // here's an additional field
    additionalField : {
      type : 'string',
      defaultsTo :'ok'
    }

  }
}
```

**Comment by tjwebb** [comment]
> just add the additional attributes you want. Like this

yep!
