### ISSUE TITLE
Question: Some newbie examples?

### ISSUE THREAD

**Issue by romu70** [tjwebb/sails-auth#117]
Hi,
I'm a back end newbie. Indeed, I'm a web development newbie even if I've a pretty long time in computing.

I've chosen Sails because it seems pretty easy, with similar concepts as in RoR, which I tried to learn some years ago. I've got a basic knowledge about those concepts from routing, MVC (which I've used on desktop apps), db layers, etc.

Authentication is a must have when we talk about web app, and as far I understood sails-auth is the Sails more or less official module which provides such a feature.

But, for a newbie, documentation is too much light. I've read the wiki, the #19 issue and so on, but that's not enough for me to be able to setup the module and, more important, to be able to check it works as expected. Which would be a proof I've done things the right way.

Of course, I don't ask you to give the whole explanation of Passport, and of each authentication providers, but a complete example, from the Js back end to some HTML would be great. Of course, I can help to improve such documentation.

Thanks.

**Comment by romu70** [comment]
Just saw the team as moved to Trails, so forget my question.

**Comment by bora89** [comment]
@romu70 Indeed, documentation very poor. Did someone figure out how to use that?
