### ISSUE TITLE
Roadmap: Migrating sails-auth to Trails.js

### ISSUE THREAD

**Issue by ronenteva** [tjwebb/sails-auth#118]
@tjwebb now that you're working on trails, should we expect no further development of sails-auth?

**Comment by tjwebb** [comment]
@ronenteva We are still maintaining the project, but any new features or major updates will be mostly likely implemented in Trails.

**Comment by tjwebb** [comment]
More info on the trails.js roadmap: https://github.com/trailsjs/trails/blob/master/ROADMAP.md

**Comment by tjwebb** [comment]
see also:
- https://github.com/tjwebb/sails-permissions/issues/200
- https://github.com/tjwebb/sails-swagger/issues/16
