### ISSUE TITLE
disable globals

### ISSUE THREAD

**Issue by jifeon** [tjwebb/sails-auth#12]
Hi, thank you for great module.

I'm not using [globals](http://sailsjs.org/#!/documentation/anatomy/myApp/config/globals.js.html) in my project, so when I include your module it falls down with error:

```
ReferenceError: sails is not defined
    at Authenticator.passport.loadStrategies (/home/jifeon/projects/adwiki/node_modules/sails-auth/api/services/passport.js:278:20)
    at Authenticator.bound [as loadStrategies] (/home/jifeon/projects/adwiki/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.initialize (/home/jifeon/projects/adwiki/node_modules/sails-auth/api/hooks/sails-auth.js:4:31)
    at Hook.bound [as initialize] (/home/jifeon/projects/adwiki/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/jifeon/projects/adwiki/node_modules/sails/lib/hooks/index.js:75:14
    at /home/jifeon/projects/adwiki/node_modules/sails/node_modules/async/lib/async.js:454:17
    at /home/jifeon/projects/adwiki/node_modules/sails/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (/home/jifeon/projects/adwiki/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Object.taskComplete (/home/jifeon/projects/adwiki/node_modules/sails/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

Could you please use module system to include sails? In this case both users are using globals and not will be able to enjoy your module :)

**Comment by tjwebb** [comment]
Yep

**Comment by tjwebb** [comment]
That line needs access to `sails.config`. I don't know how else to get access to this.

A lot of extensions are going to rely on `sails` being global.

**Comment by jifeon** [comment]
Why you can't just use something like 
```js
require('sails').config;
```

This code may seems strange but in reality sails-auth always depends on sails, and can be used only as plugin for sails. So require('sails') always will return sails instance. Btw, I think it's needed to add sails as peer dependency.

One more thing. I can accept that `sails` is global var because the plugins itself for sails, but services as global variables can cause errors. Furthermore `passport` here is the service and the name of library, so it becomes ambiguous. You can access it through `sails.services`

**Comment by tjwebb** [comment]
> require('sails').config;

I'm not going to do this, sorry. sails already is a peerDependency; make sure you have the latest version of sails-auth.

> but services as global variables can cause errors. 

Is there a bug report for this? If this causes issues, sails team should fix it.

I'm much more inclined to follow sails convention than to bend over backward to support every possible configuration.

**Comment by jifeon** [comment]
Globals causes problems and it's not a problem of sails anymore since the authors implemented ability to disable spreading global variables in v.0.10

You can read [here](https://github.com/balderdashy/sails/issues/295) and [here](https://github.com/balderdashy/sails/issues/2583) about the sails users' problems related to globals. And now some users start using sails without globals to avoid these problems. And when they want to use your module they will face another problem..

I can get your point of view, but in any case I am going to fork your repo to fix it for myself. If you want I can create PR after it.

**Comment by tjwebb** [comment]
re: https://github.com/balderdashy/sails/issues/295#issuecomment-16016521

Alright I'll follow @mikermcneil's lead and rely only on the global `sails` object, and everything else will be accessed via `sails.<service>` and so forth. Sound good?

**Comment by jifeon** [comment]
Yeah! It would be absolutely great, thank you!

**Comment by tjwebb** [comment]
update: I've removed some but not all occurrences. Do you have some time to go through and replace the remaining globals? There's not a ton of code here, I'm just not going to have time for the next few days to look at this.

**Comment by jifeon** [comment]
Yep, I can do it on weekend )

**Comment by tjwebb** [comment]
@jifeon any progress?

**Comment by jifeon** [comment]
Sory for delay..
