### ISSUE TITLE
sails.getBaseUrl() is deprecated

### ISSUE THREAD

**Issue by max918** [tjwebb/sails-auth#126]
warn: sails.getBaseUrl() is deprecated and will be removed in Sails v1.0.  See http://sailsjs.org/documentation/reference/application/sails-getbaseurl for more info.

**Comment by tjwebb** [comment]
It sure is.

**Comment by tjwebb** [comment]
I don't know why the links keep changing on the Sails website. The correct URL for getBaseURL is http://sailsjs.org/documentation/reference/application/sails-get-base-url
