### ISSUE TITLE
Is there any documentation as to how to use this package?

### ISSUE THREAD

**Issue by thescopan** [tjwebb/sails-auth#131]
I am new to sails and the first thing I wanted to implement was auth. But the readme does not explain anything about the usage.

**Comment by subwaymatch** [comment]
+1. Wishing for a documentation or some kind of example.

**Comment by aamistak** [comment]
+1

**Comment by tjwebb** [comment]
There is documentation here: https://github.com/tjwebb/sails-auth/wiki

Contributions are welcome and encouraged. Believe it or not, there's an actual limit to how much work I can do for free.
