### ISSUE TITLE
make installable hook 

### ISSUE THREAD

**Issue by tjwebb** [tjwebb/sails-auth#18]
http://sailsjs.org/#!/documentation/concepts/extending-sails/Hooks/installablehooks.html

**Comment by eddieajau** [comment]
Would it be possible to organise a hangout to perhaps discuss making this the "one auth to rule them all" solution and developing a roadmap for interested parties to work on? 

I'm particularly interested in finding an installable hook solution for auth, but it also needs to be able to handle the option of not needing sessions (for example, for a RESTful JSON server). There's also the issue that a default `User` model and controller may need to be extended per implementation.

Thanks in advance.

**Comment by tjwebb** [comment]
I've updated the module to indicate that it's officially supported by Balderdash: https://github.com/tjwebb/sails-auth#maintained-by. We can't force everyone to use the same thing, but hopefully our backing will help drive adoption of our solution.
