### ISSUE TITLE
Middleware not initialized

### ISSUE THREAD

**Issue by claymcleod** [tjwebb/sails-auth#26]
Hey TJ,

Following the steps to install sails-permissions, I receive this error

```
/SailsJSApp/node_modules/sails-auth/node_modules/passport/lib/http/request.js:44
    if (!this._passport) { throw new Error('passport.initialize() middleware n
                                 ^
Error: passport.initialize() middleware not in use
    at IncomingMessage.req.login.req.logIn (/SailsJSApp/node_modules/sails-auth/node_modules/passport/lib/http/request.js:44:34)
    at /SailsJSApp/node_modules/sails-auth/api/controllers/AuthController.js:93:11
    at Strategy.strategy.success (/SailsJSApp/node_modules/sails-auth/node_modules/passport/lib/middleware/authenticate.js:194:18)
    at verified (/SailsJSApp/node_modules/sails-auth/node_modules/passport-google/node_modules/passport-openid/lib/passport-openid/strategy.js:194:14)
```

Seems like a relatively simple fix, but since Sails handles middleware configuration, I thought I would post here to get your thoughts on the issue.

**Comment by tjwebb** [comment]
same as https://github.com/tjwebb/sails-auth/issues/25

Initializing should occur in the `passport` policy. Is `passport` in your policies list?

**Comment by claymcleod** [comment]
Here is my policies.js for your reference:

```
 module.exports.policies = {

   '*': [
   'basicAuth',
   'passport',
   'sessionAuth',
   'ModelPolicy',
   'AuditPolicy',
   'OwnerPolicy',
   'PermissionPolicy',
   'RolePolicy'
   ],

   AuthController: {
    '*': true
  }
};
```

**Comment by claymcleod** [comment]
Updated the original post with a more detailed error report. I tried looking for the answer, but to no avail.

**Comment by tjwebb** [comment]
Do you have the file api/hooks/sails-auth.js? That's where loadStrategies should occur

**Comment by claymcleod** [comment]
Here is a link to a clean project in which the problem was reproduced: https://github.com/claymcleod/testing-sails-permissions

**Comment by tjwebb** [comment]
ok thanks

**Comment by claymcleod** [comment]
Let me know if i can do anything else to help. Right now I'm clueless.

**Comment by tjwebb** [comment]
You don't have sails-permissions or sails-auth in your package.json, so I can't figure out what version you're using. Can you re-install sails-permissions through npm with `--save`

**Comment by claymcleod** [comment]
Done. (Still can reproduce)

**Comment by tjwebb** [comment]
Crap, my bad. The sails-permissions and sails-auth documentation got out of sync. The AuthController policy should look like this: https://github.com/tjwebb/sails-auth#configpoliciesjs.

sails-permissions README is wrong. Really sorry about that.

**Comment by claymcleod** [comment]
That fixed it. Thanks, TJ

**Comment by tjwebb** [comment]
Awesome, thanks for letting me know.
