### ISSUE TITLE
Email not transferred to SailsJS

### ISSUE THREAD

**Issue by willemmulder** [tjwebb/sails-auth#36]
I implemented sails-auth using the below in the passports.js file

```
passport : {
        twitter : {
            name : 'twitter',
            protocol:'oauth',
            strategy:require('passport-twitter').Strategy,
            options:{
                consumerKey:'...',
                consumerSecret:'...'
            }
        }
    }
```

The twitter app has read/write permissions on my twitter profile. The auth also works, but then Sails crashes, because in User.js it tries to generate the Gravatar URL with 'this.email' which is not set at all. The generated user looks like this

```
{
  "owner": 3,
  "username": "WillemMulder",
  "id": 3,
  "createdAt": "2015-04-07T17:05:04.120Z",
  "updatedAt": "2015-04-07T17:05:04.212Z"
}
```

Any clue why the email might not be filled?

**Comment by tjwebb** [comment]
Do you mind filing this in https://github.com/tjwebb/sails-auth? I can help you out over there. Thanks.

**Comment by willemmulder** [comment]
But... I just did :-) 

Did you mean some other repo?
