### ISSUE TITLE
Passport Policy Suggestion

### ISSUE THREAD

**Issue by scott-wyatt** [tjwebb/sails-auth#37]
@tjwebb I've been digging around a lot of different implementations of Passport.js into sails, and I've found this really useful.  By updating policies/passport.js to this, it will allow socket passport authentication which I am seeing more and more of.

```js
// policies/passport.js
var http = require('http');
var methods = ['login', 'logIn', 'logout', 'logOut', 'isAuthenticated', 'isUnauthenticated'];
module.exports = function (req, res, next) {
  // Initialize Passport
  passport.initialize()(req, res, function () {
    // Use the built-in sessions
    passport.session()(req, res, function () {
      // Make the user available throughout the frontend
      res.locals.user = req.user;
      // Make the request's passport methods available for socket
      if (req.isSocket) {
        for (var i = 0; i < methods.length; i++) {
          req[methods[i]] = http.IncomingMessage.prototype[methods[i]].bind(req);
        }
      }
      next();
    });
  });
};
```
I've just tested this using:
Sails: 0.11.0
sails-auth: 1.0.8

**Comment by tjwebb** [comment]
> socket passport authentication which I am seeing more and more of.

I'd love to incorporate this; would you like to submit a PR with this feature, along with a basic test showing how it works? Then I can update the docs and publish a new version with your improvements.

Thanks!

**Comment by scott-wyatt** [comment]
Sure thing, will do.

**Comment by scott-wyatt** [comment]
I've submitted a PR I ran a Mocha test on it and it passed (but again, I'm not great at the testing yet and any feedback is much appreciated). Super easy to add to your workflow and is great for things like Modal Logins or Login Confirmations especially while working with single page apps.  Personally I use angularSails with it, but you can do it with stock sails as well:
It accepts `'login', 'logIn', 'logout', 'logOut', 'isAuthenticated', 'isUnauthenticated'`   
```js
//Login Example
io.socket.post('/auth/local', {
          identifier: 'existing.user@email.com',
          password: 'admin1234'
      }, function (resData) {
          //Returns either and error or JSON object of logged in User, which means the users subsequent AJAX requests will be authenticated. If you have CORS enabled you'll want to send a prerequisite socket request to get that first and then add it to your following socket requests.
      });
```

**Comment by scott-wyatt** [comment]
@tjwebb, this can be closed, it was fixed with the lastest merge.
