### ISSUE TITLE
Documentation would be greatly appreciated

### ISSUE THREAD

**Issue by vmaatta** [tjwebb/sails-auth#4]
I've been trying to bring sails-auth into an existing project and I have to say this is more painful due to the lack of documentation. There's good promise in sails-auth but can the project in its current state to really be used? If so, what exact steps does one need to do, what exactly needs to be implemented by hand and what does sails-auth implement.

1. How to get registration and login working with simple local auth. I'm basically just hitting 404s and from /auth/local/register for example. Yeah, clearly templates are not provided but the feeling I have right now is: "is anything else either"?
2. How to implement simple bearer authentication. Whether with oauth2 or just raw passport-http-bearer, what needs to be implemented to just authenticate the user.

I'm fine with manually adding tokens to users. All I want is to validate that this thing is going to work and to do that I need to know what templates / callbacks etc. need to be implemented and where.

PS. A note about the need to add ```"auth-api": "sails-auth"``` to ```.sailsrc``` would be good.

**Comment by tjwebb** [comment]
I've recently published a lot of new documentation for sails-auth and sails-permissions. I hope you find it useful.

**Comment by cyrilchapon** [comment]
> How to get registration and **login** working with simple local auth. I'm basically just hitting 404s and from /auth/local/register for example. Yeah, clearly templates are not provided but the feeling I have right now is: "is anything else either"?

This is not aswered by any documentation in here, is it ?
