### ISSUE TITLE
Major issue, Google no longer supports OpenID 2.0

### ISSUE THREAD

**Issue by secrettriangle** [tjwebb/sails-auth#42]
Getting https://support.google.com/accounts/answer/6206245?p=openid&rd=1 on connect, Google auth is completely broken.

**Comment by tjwebb** [comment]
Yikes; I think you might need to use a different passportjs provider for google

**Comment by tjwebb** [comment]
@secrettriangle try installing the `passport-google-oauth` module and replacing the `passport-google` require statement in config/passport.js. If that works for you, I'll push a fix today.

**Comment by secrettriangle** [comment]
I also found [jaredhanson/passport-openidconnect](https://github.com/jaredhanson/passport-openidconnect) by the same guy but my familiarity with OpenID and OAuth is cursory at best so I was not able to set it up.

**Comment by tjwebb** [comment]
You tried both passport-google-oauth and passport-openidconnect?

I'll look at it this weekend

**Comment by secrettriangle** [comment]
I haven't tried both... I don't know how to use openidconnect. The PR is for OAuth2.
