### ISSUE TITLE
How to GET current user?

### ISSUE THREAD

**Issue by secrettriangle** [tjwebb/sails-auth#45]

**Comment by tjwebb** [comment]
what does "current" user mean? There could be 50 people logged in at once.

**Comment by secrettriangle** [comment]
I want to determine who "I" am on load. I can store the username via cookie/localstorage/whatever but maybe it's cleaner to have some sort of controller that simply returns JSON of `req.user`?

**Comment by tjwebb** [comment]
Oh ok; like, if the browser authenticates with some pre-existing session, I want to query whatever user that session belongs to.

I think by default you should be able to query the list of all users and only get back yourself in the list (if you have a session). If that doesn't work, I might have another bug somewhere.

**Comment by secrettriangle** [comment]
Doesn't seem like it works. Doesn't sound very semantically correct anyway. Maybe we should add a `/user/me` endpoint?
