### ISSUE TITLE
hashPassword should not rehash a password that is already a bcrypt hash

### ISSUE THREAD

**Issue by kplatter** [tjwebb/sails-auth#66]

**Comment by tjwebb** [comment]
detecting a hash is not really possible. "abc123" is a possible hash, but could also be someone's password.

**Comment by kplatter** [comment]
A bcyrpt hash has a defined format see http://stackoverflow.com/questions/5393803/can-someone-explain-how-bcrypt-verifies-a-hash/10933491#10933491

**Comment by tjwebb** [comment]
That doesn't solve the problem. see: https://github.com/tjwebb/sails-auth/blob/master/api/models/Passport.js#L12

What if a password is hashed with a different salt, or salt length? It'll look like a bcrypt password, but the comparison wouldn't work. Sorry, there's just no way I'm going to conditionally allow some passwords to enter the database un-hashed.

**Comment by kplatter** [comment]
I was basing the detection off of $2a$%%$ and then any length after that, which would not care about salt or salt length.  Yes it is possible that a user could have a password of $2a$10$.... but how likely is that?  I have other users other than admin that I need to add and I don't store their password unhashed.  As it is there is no option for adding them to the database without having their unhashed password.  What if there was an attribute on the passport that indicated whether or not it should be hashed and then "delete passport.passwordAlreadyHashed"?

**Comment by tjwebb** [comment]
> I have other users other than admin that I need to add and I don't store their password unhashed.

You can send it in through the REST interface (`/user/create`, etc). This is just adding users in the typical way. Is there some other web service that you're used to which lets you send it pre-hashed user passwords? I've never seen this before. 

> Yes it is possible that a user could have a password of $2a$10$.... but how likely is that?

That's not up to me to decide. People use all kinds of passwords with all kinds of special characters and various craziness. Creating a separate, special process for already-hashed passwords just opens up an additional attack vector. The goal of this module is, after all, security.

**Comment by kplatter** [comment]
SQL Server supports it see https://msdn.microsoft.com/en-us/library/ms189751.aspx

Oracle supports it see http://docs.oracle.com/cd/E17952_01/refman-5.5-en/create-user.html

MySQL supports it see http://www.techonthenet.com/mysql/users/create_user.php

I'm not sure how supplying a hashed password opens an attack vector any more than sending a clear text one does.  Each of the cases above provide options for supplying it either way, but it is stored as hashed.

**Comment by tjwebb** [comment]
From the SQL Server docs: 
> This option should only be used for migrating databases from one server to another. Do not use the HASHED option to create new logins.

There's a good reason for this, which I've mentioned. Here, **you** are migrating data, which is fine for you. This module is not designed to help you migrate data. It is designed to authenticate users.

**Comment by kplatter** [comment]
They still provide the option, and these are not new logings but existing ones.  In any case, I'm not sure how to extend since the function is on the Passport model.  I guess I can create a new model for the Passport named PassportHash that has the same attributes and update the password without the rehashed password after the user is registered?

**Comment by kplatter** [comment]
I overrode the beforeCreate, and beforeUpdate functions in api\models\Passport.js, is there some other more sailsish way to do it?

**Comment by tjwebb** [comment]
Yea, currently the hashing is done in `Passport.beforeCreate`. You can override the `beforeCreate` function just by defining one in your local `api/models/Passport.js` inside the merge block. My implementation might look something like this:

```js
{
  // ...
  beforeCreate: function (passport, next) {
    if (!passport.skipHash && passport.matchBcryptFormat(passport.password) {
      hashPassword(passport, next);
    }
    else {
      next();
    }
  }
}
```
