### ISSUE TITLE
passport model should provide option to not rehash a password

### ISSUE THREAD

**Issue by kplatter** [tjwebb/sails-auth#67]
#66 I was basing the detection off of $2a$%%$ and then any length after that, which would not care about salt or salt length.  Yes it is possible that a user could have a password of $2a$08$.... but how likely is that?

I have other users other than admin that I need to add when the system is initialized and I don't have their unhashed password.  As it is there is no option for adding them to the database without having their unhashed password.

What if there was an attribute on the passport that indicated whether or not it was already hashed and then "delete passport.passwordAlreadyHashed"?

**Comment by tjwebb** [comment]
> and I don't have their unhashed password.

You mean you have passwords already encrypted by another system, in some other database somewhere? This module is designed to enable user authentication; it's not designed to be an ETL layer for migrating users from other sources. The correct approach here is to simply require users to update their passwords, and re-hash them at that time.
