### ISSUE TITLE
Just starting out. Validation issues

### ISSUE THREAD

**Issue by MishY111** [tjwebb/sails-auth#81]
I have added the following to api/models/User.js

    // api/models/User.js
    var _ = require('lodash');
    var _super = require('sails-permissions/api/models/User');
    
    _.merge(exports, _super);
    _.merge(exports, {
    // Extend with custom logic here by adding additional fields, methods, etc.
    schema: true,

    attributes: {
      firstname: {
        type: 'string',
      required: true,
      notNull: true
	},
	lastname: {
	  type: 'string',
      required: true,
      notNull: true
	}
    }
    });

In what I hoped would enable me to just expand upon the default user profile. Whenever I post to /user sails returns with:

{
  "status": 400,
  "summary": "Encountered an unexpected error",
  "invalidAttributes": {
    "firstname": [
      {
        "message": "`undefined` should be a string (instead of \"null\", which is a object)"
      },
      {
        "message": "\"required\" validation rule failed for input: null"
      },
      {
        "message": "\"notNull\" validation rule failed for input: null"
      }
    ],
    "lastname": [
      {
        "message": "`undefined` should be a string (instead of \"null\", which is a object)"
      },
      {
        "message": "\"required\" validation rule failed for input: null"
      },
      {
        "message": "\"notNull\" validation rule failed for input: null"
      }
    ]
  }
}

I am POSTing with Postman the following:

http://localhost:1337/user?username=test&email=me@me.com&password=supersecure&firstname=sails&lastname=js

Am I wrong to append extra attributes to this file?

Furthermore, on a fresh install if I login using the admin@example.com account and post: http://localhost:1337/user?username=travis&email=travis@theemail.com&password=secretpassword

It returns:

{
  "createdBy": 1,
  "owner": 1,
  "createdAt": "2015-08-20T10:48:58.434Z",
  "updatedAt": "2015-08-20T10:48:58.434Z",
  "id": 9,
  "gravatarUrl": "https://gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e"
}

With none of the extra fields? I'm sure I'm missing something simple here ^^

Thanks

**Comment by MishY111** [comment]
I wonder if this is related to this bug: https://github.com/tjwebb/sails-permissions/issues/110

(Sorry if this issue should have been raised in sails-permissions).

I did the fix when setting up sails-permissions and sails-auth in order to get the generator working, but wonder if the generator generates config files that don't have the right paths following the fix.

**Comment by MishY111** [comment]
I don't believe the above issue relates to this having tested more.

**Comment by ryanwilliamquinn** [comment]
I would try putting all of those parameters into the post request body, rather than the query string.  Let me know if that makes any difference for you.

**Comment by MishY111** [comment]
Thank you. You were absolutely right.
